const TOGGLE_TODO = 'TOGGLE_TODO'
const ADD_TODO = 'ADD_TODO'
const UPDATE_ADD_TODO = 'UPDATE_ADD_TODO'
const ADD_LOG = 'ADD_LOG'

export {
    TOGGLE_TODO,
    ADD_TODO,
    UPDATE_ADD_TODO,
    ADD_LOG
}
