const TOGGLE_TODO = 'TOGGLE_TODO'
const ADD_TODO = 'ADD_TODO'
const UPDATE_ADD_TODO = 'UPDATE_ADD_TODO'
const ADD_LOG = 'ADD_LOG'
const FETCH_TODO = 'FETCH_TODO'
const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
const SUBMIT_TODO = 'SUBMIT_TODO'
const SUBMIT_TODO_SUCCESS = 'SUBMIT_TODO_SUCCESS'

export {
    TOGGLE_TODO,
    ADD_TODO,
    UPDATE_ADD_TODO,
    ADD_LOG,
    FETCH_TODO,
    FETCH_TODO_SUCCESS,
    SUBMIT_TODO,
    SUBMIT_TODO_SUCCESS
}
